### PR TITLE
Em dash

### PR DESCRIPTION
**Pull request by ajschumacher**
just changing some formatting some things for fun; see commits

### CODE REVIEW

**Comment by millzpaugh** [comment]
@ajschumacher Thanks, these are great!

**Comment by ajschumacher** [comment]
ah noooo merge conflicts now tho

**Comment by ajschumacher** [comment]
Hi @millzpaugh! Do you want to close this? With or without the joy of em dashes? :dash: :wavy_dash:

**Comment by millzpaugh** [comment]
@ajschumacher Sorry about that. Thought I had already merged it! Finished. :)

**Comment by ajschumacher** [comment]
em dash 4 life

**Pull request merged**
